arr=[99,4,66,1,7]
print(arr)
arr.sort()
print(arr)
arr.append(100)
print(arr)
arr.insert(2,8)
print(arr)
arr.remove(100)
print(arr)
arr.reverse()
print(arr)
res=sum(arr)
print(res)
print('the largest element in athe array is',max(arr))
